global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redpanda'
    metrics_path: /metrics
    static_configs:
      - targets: ['redpanda:9644']

  - job_name: 'airflow_statsd'
    static_configs:
      - targets: ['statsd-exporter:9102']

  - job_name: 'airflow_prom'
    metrics_path: /metrics
    static_configs:
      - targets: ['airflow:8082']


  - job_name: redpanda
    static_configs:
      - targets: ['redpanda:9644']